const productData = [
    {
        productID: "P001",
        productName: "iPhone 5",
        productBrand: "Apple",
        price: 399,
        quantity: 10,
        description: "lorem 1",
        provider: "FPT Telecom",
    },
    {
        productID: "P002",
        productName: "iPhone 6",
        productBrand: "Apple",
        price: 599,
        quantity: 9,
        description: "lorem 2",
        provider: "Viettel",
    },
    {
        productID: "P003",
        productName: "iPhone 7",
        productBrand: "Apple",
        price: 699,
        quantity: 45,
        description: "lorem 3",
        provider: "Thegioididong",
    },
    {
        productID: "P004",
        productName: "iPhone 8",
        productBrand: "Apple",
        price: 799,
        quantity: 34,
        description: "lorem 4",
        provider: "FPT Telecom",
    },
    {
        productID: "P005",
        productName: "iPhone X",
        productBrand: "Apple",
        price: 999,
        quantity: 8,
        description: "lorem 5",
        provider: "FPT Telecom",
    },
    {
        productID: "P006",
        productName: "Samsung galaxy S10",
        productBrand: "Samsung",
        price: 1500,
        quantity: 12,
        description: "lorem 6",
        provider: "Thegioididong",
    },
    {
        productID: "P007",
        productName: "Samsung galaxy A71",
        productBrand: "Samsung",
        price: 400,
        quantity: 14,
        description: "lorem 7",
        provider: "FPT Telecom",
    },
    {
        productID: "P008",
        productName: "OPPO Reno3",
        productBrand: "OPPO",
        price: 199,
        quantity: 32,
        description: "lorem 8",
        provider: "Viettel",
    },
    {
        productID: "P009",
        productName: "OPPO A92",
        productBrand: "OPPO",
        price: 299,
        quantity: 46,
        description: "lorem 9",
        provider: "FPT Telecom",
    },
    {
        productID: "P010",
        productName: "Samsung galaxy note 9",
        productBrand: "Samsung",
        price: 399,
        quantity: 25,
        description: "lorem 10",
        provider: "Thegioididong",
    }
];